name: Firebase CD

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4

     - name: set up JDK 17
       uses: actions/setup-java@v4
       with:
          distribution: 'zulu'
          java-version: '17'

     - name: Make gradlew executable
       run: chmod +x ./gradlew

     - name: Gradle cache
       uses: actions/cache@v4
       with:
         path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
         restore-keys: |
          ${{ runner.os }}-gradle-

     - name: Access Google-Service file
       run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

     - name: Build with Gradle
       run: ./gradlew assembleDebug

     - name: upload artifact to Firebase App Distribution
       uses: wzieba/Firebase-Distribution-Github-Action@v1
       with:
         appId: ${{secrets.FIREBASE_APP_ID}}
         serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
         groups: testers
         file: app/build/outputs/apk/debug/app-debug.apk
